### ISSUE TITLE
Borrow system problems

### ISSUE THREAD

**Issue by henninglive** [evenorog/redo#1]
I feel like the interface provided by this crate doesn’t work very well with Rust’s borrow system. The problem is that each command is expected to hold a mutating reference to the receiver. This could lead to aliasing writes, and is exactly what the rust borrow systems tries to avoid. This is why you ended up using unsafe in your readme example. Safe rust won’t allow you to do this unless you use something like `std::cell::RefCell` or `std::sync::Mutex`, which allow you to mutate through immutable references.

I suggest the following changes to make the interface work better with the borrow system.

```rust
trait Command<T> {
    type Err;
    fn forward(&mut self, receiver: &mut T) -> Result<(), Self::Err>;
    fn backwards(&mut self, receiver: &mut T) -> Result<(), Self::Err>;
}

struct CommandStack<T, C: Command<T>>{
    stack: Vec<C>,
    receiver: T,
}

impl<T, C: Command<T>> CommandStack<T, C> {
    fn new(receiver: T) -> CommandStack<T, C> {
        CommandStack {
            stack: Vec::new(),
            receiver: receiver,
        }
    }

    fn push(&mut self, mut command: C) -> Result<(), C::Err> {
        command.forward(&mut self.receiver)?;
        self.stack.push(command);
        Ok(())
    }

    fn pop(&mut self) -> Option<Result<C, (C, C::Err)>> {
        let mut c = match self.stack.pop() {
            Some(c) => c,
            None => return None,
        };
        match c.backwards(&mut self.receiver) {
            Ok(_) => Some(Ok(c)),
            Err(e) => Some(Err((c, e))),
        }
    }
}
```

This lets the stack control invocations of commands, we limit the lifetime of the `&mut` reference to the invocation of that command and we guaranty serialized execution.

**Comment by evenorog** [comment]
I agree that the current interface does not work well with the borrow system, and you most likely would have to use interior mutability.

I think this is a good solution! That the stack owns the object instead of having to keep a `&mut` in the command solves much of the borrowing issues i think.

Thank you!

**Comment by henninglive** [comment]
Yeah, probably. It is a cleaner interface, but the user is forced to track popped commands themselves, if they want to reapply them. Keeping unapplied commands also has its problems. What happens if the user pushes a change while the stack contains unapplied commands? Are they still valid? Think text editor.

**Comment by henninglive** [comment]
Maybe provide two or even three abstractions. The first one a simple stack, then a history list like current one and maybe even tree history like the emacs undo tree.

**Comment by evenorog** [comment]
Yeah sounds like a good idea. I'll let the stack take ownership to begin with, to fix the borrowing issues. Then I will look into the other ways of moving through the stack.

**Comment by henninglive** [comment]
Sounds good. I would also drop the `Redo` prefix from your names of your types, prefixes like these are against the rust [naming convention](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html#avoid-redundant-prefixes-[rfc-356]).

**Comment by evenorog** [comment]
Oh right, I'll do that too!

I really appreciate the feedback, thanks!
