### ISSUE TITLE
Remove the target from the Record struct and pass it by reference

### ISSUE THREAD

**Issue by Dollab** [evenorog/redo#7]
Hi, Thank you for this very nice crate.

In order to be able to use this crate in a more general manner, it could be useful to pass a mutable reference of the `Target` struct rather than store it as an owned value in the `Record ` struct. 

In a real life application the state is likely to be represented by a somewhat complex struct that cannot be owned or mutably borrowed by a `Record`.

I've modified your crate in this way in a local fork in order to use it on a personal project. The modifications are rather simple : 
1. remove the target field on the Record Struct
2. add a `&mut C::Target` parameter to every method modifying the target
3. delete all methods returning a reference to the target
This create a  somewhate less elegant api where you have to pass the target reference to each method call but it'a simple and robust way to decouple the undo/redo mechanism to the state its applied on.

If this modification is something that you would consider, I'll be happy to submit a PR.

**Comment by evenorog** [comment]
Hi! 

Thanks for the suggestion, i'm not able to test this out right now but i'll try to check it out in the coming weeks. 

I'm thinking this might be a good api for the `undo` library and then this library could build on top of `undo`, or something like that.

I'll leave this issue open and comment here when i have the time to test it out!

**Comment by evenorog** [comment]
`undo` is using this approach now :+1:
